# Generated by Django 4.0.5 on 2022-08-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='movie_selection.nomination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_selection.room')),
            ],
        ),
        migrations.AddField(
            model_name='nomination',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_selection.room'),
        ),
    ]
