# Generated by Django 4.0.5 on 2022-07-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
