# Generated by Django 4.0.5 on 2022-07-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0002_alter_nomination_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_selection.nomination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_selection.room')),
            ],
        ),
    ]
