# Generated by Django 4.0.5 on 2022-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='yes',
        ),
        migrations.AddField(
            model_name='nomination',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
