# Generated by Django 4.0.5 on 2022-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0004_remove_nomination_name_remove_vote_yes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='room',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
