# Generated by Django 4.0.5 on 2022-08-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0005_remove_vote_room_alter_vote_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='val',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='movie_selection.room'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='movie_selection.nomination'),
        ),
    ]
