# Generated by Django 4.0.5 on 2022-08-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_selection', '0006_rename_vote_vote_val_alter_nomination_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='val',
            new_name='vote',
        ),
    ]
